Repository invoiceninja/invoiceninja, pull requests merged in 2024-11, with the labels that each got.

#10244 Improve compatibility with CIUS XRechnung schema
  app/Services/EDocument/Standards/ZugferdEDokument.php
Labels: pending merge

#10272 E-invoicing: Fixes for acting validators
  app/Http/Requests/EInvoice/Peppol/UpdateEntityRequest.php
  lang/en/texts.php
Labels: feedback

#10278 Update translations
  lang/en/texts.php
Labels: qa pending

#10296 Include einvoicing token in the headers
  app/Services/EDocument/Jobs/SendEDocument.php
Labels: qa pending

#10301 Sync updating local quota value for self-hosted
  app/Http/Controllers/EInvoiceController.php
  app/Services/EDocument/Gateway/Storecove/StorecoveProxy.php
  app/Services/EDocument/Jobs/SendEDocument.php
Labels: qa pending
